#!/usr/bin/env python3

import os
import vdf
import subprocess
import time

class NoUsersFound(Exception):
    pass

#return players
def getUsers(STEAMCONFIG: str) -> list[dict]:
    usersList = []

    path = os.path.join(STEAMCONFIG, "loginusers.vdf")

    if not os.path.exists(path):
        raise NoUsersFound("Dados de usuarios não encontrado")

    with open(path, 'r', encoding="utf-8") as f:
        data = vdf.load(f)

        for user, dados in data["users"].items():

            userDict = {
                "ID": user, 
                "UserName":dados.get("PersonaName"), 
                "AccountName":dados.get("AccountName")
                }
            
            usersList.append(userDict)
        
    return usersList
#---      

def selectUser(users: list[dict]) -> str:
    print("Usuarios disponiveis: ")

    for i, user in enumerate(users, 1):
        print(f"[{i}] {user["AccountName"]}({user["UserName"]})")
    
    choice = input("Digite o codigo do usuario: ")

    return int(choice) - 1



#return games list
def getGames(STEAMAPPS: str) -> list[tuple[int, str]]:
    games = []

    for file in os.listdir(STEAMAPPS):
        if file.startswith("appmanifest") and file.endswith(".acf"):
            path = os.path.join(STEAMAPPS, file)

            with open(path, 'r', encoding="utf-8") as f:
                data = vdf.load(f)["AppState"]

                if data.get("DownloadType") == "0" or data.get("name").startswith("Steam Linux Runtime"):
                    continue

            appid = data["appid"]
            name = data["name"]

            appid = int(appid)

            games.append((appid, name))

    games.sort(key=lambda x: x[1])

    return games
#---

#game choice
def getChoice(games: list[tuple[int, str]]) -> int:
    print("Jogos instalados:\n")
    for i, game in enumerate(games, 1):
        print(f"[{i}] {game[1]}")

    choice = input("\nDigite o codigo do jogo: ")
        
    return int(choice) - 1
#---

#process
def runGame(choice: int, games: list[tuple[int, str]]) -> None:
    index = choice
    appid = games[index][0]

    if subprocess.call(["pgrep", "-x", "steam"],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL
                ) != 0:

        subprocess.Popen(["steam", "-silent"],
                    )

        while subprocess.call(["pgrep", "-x", "steamwebhelper"],
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL
                    ) != 0:

            time.sleep(1)

        time.sleep(3)
    
    subprocess.Popen(
        ["steam", f"steam://rungameid/{appid}"],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL
    )
#---

if __name__ == "__main__":
    #globais
    STEAM_PATH = os.path.expanduser("~/.local/share/Steam/")
    STEAMAPPS = os.path.join(STEAM_PATH, "steamapps")
    STEAMCONFIG = os.path.join(STEAM_PATH, "config")
    #---

    users = getUsers(STEAMCONFIG)

    userID = selectUser(users)

    '''try:
        gamelist = getGames(STEAMAPPS)

        playerChoice = getChoice(gamelist)

        runGame(playerChoice, gamelist)

    except ValueError:
        print("Entrada inválida: digite um número.")

    except IndexError:
        print("Código inválido: jogo não existe na lista.")

    except FileNotFoundError:
        print("Steam não encontrada no sistema.")

    except Exception as e:
        print(f"Erro inesperado: {e}")'''
